### ISSUE TITLE
System total freeze when used with COMODO antivirus

### ISSUE THREAD

**Issue by cosmincrihan** [slavaim/redirfs#12]
I installed kernel 4.14.78 to test the current RedirFS version with the COMODO antivirus. The original RedirFS driver provided with it only compiles on kernel < 2.6, so I wanted to give it a try. Successfully compiled, installed and loaded the module, but 2 seconds after "modprobe avflt" and COMODO starting to use the redirfs and avflt modules, the whole system freezes as if it cannot read any file from the disk. I cannot even login from other tty, the only solution being to restart and boot with another kernel.
Is it not compatible with COMODO for some reason?

**Comment by slavaim** [comment]
I think yes. You need to contact COMODO to clarify this.

**Comment by cosmincrihan** [comment]
All right, thank you for the response!
