### ISSUE TITLE
Question about multiple redirfs

### ISSUE THREAD

**Issue by her0gyu** [slavaim/redirfs#13]
I change the Redirfs Exported symbol name and sysfs name things and kmem_cache names things.
And I loaded two redirfs module. After that I registered  kernel module into each redirfs filter.
And I added the path each of them. 
When I tried to add path of second redirfs-registered kernel module. panic happened
so my question is, is it possible to make two redirfs load on two kernel, and to make operate well?

**Comment by slavaim** [comment]
I don't think it is viable. Theoretically it is possible with some modifications but the original design was not made with multiple redirfs modules in mind. The idea was that you can register multiple filters with a single redirfs which manages them, i.e. redirfs is a manager for multiple filters so you can register all your filters with a single copy of redirfs. Multiple managers were not in original design.
