### ISSUE TITLE
win like path

### ISSUE THREAD

**Issue by mincau** [slavaim/redirfs#8]
Can redirfs redict win path to file on Linux? for exmaple,
One process read "c:\test\test.txt"， the read file it read located "/mnt/test/test.txt"

**Comment by slavaim** [comment]
I didn't get it. If you want to redirect from a Windows machine to a Linux machine you need a filter on the Windows machine which has nothing to do with a Linux filter. If you are talking about WSL (Windows Subsystem for Linux) then again it has nothing to do with Linux kernel as this subsystem doesn't contain Linux kernel. If you want to emulate Windows subsystem on Linux you better look for WINE.
